dataset_path: data
seed: 42
best_model_path: "checkpoints/best_model_20240717165029.pth"
num_epoch: 50
num_frames: 2
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 8
    shuffle: false
  test:
    batch_size: 1
    shuffle: false
train:
  num_frames: 2
  no_batch_norm: false
  initial_learning_rate: 0.02
  weight_decay: 0.0001
  epochs: 50
